[client]
showSidebarNavigation = true
[server]
runOnSave = true
[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#2E2E2E"
textColor = "#FFFFFF"
font = "sans serif"
